commands:
  testLearning:
    # The description of the command
    # All colors : http://minecraft.gamepedia.com/Formatting_codes

    # The color of the message
    color: "ยง2"
    # The message to send to the player
    message: Learning is enabled!