name: Learning
version: 1.0
api-version: 1.19
main: me.gamcross.learning.Main

commands:

  broadcast:
    description: Broadcasts a message to the server
    aliases: [bc]
    permission: learning.broadcast

  testLearning:
    description: Tests if Learning is enabled
    aliases: [tl]
    permission: learning.test